apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: 02--pod
  labels:
    app: nginx
    course: "k8s-crash-course"
    section: "02-1-Pods"
  annotations:
    description: "Secure NGINX standalone pod using Chainguard image."
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: cgr.dev/chainguard/nginx:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 8080
      resources:
        limits:
          memory: "50Mi"
        requests:
          cpu: "250m"
          memory: "25Mi"
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
