apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  namespace: 02--replicaset
  labels:
    app: nginx
    course: "k8s-crash-course"
    section: "02-2-Replicas"
  annotations:
    description: "Production-like ReplicaSet running hardened NGINX."
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        course: "k8s-crash-course"
        section: "02-2-Replicas"
      annotations:
        description: "Secure NGINX pod running on port 8080."
    spec:
      containers:
        - name: nginx
          image: cgr.dev/chainguard/nginx:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              cpu: "250m"
              memory: "50Mi"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
