apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: 02--deployment
  labels:
    app: nginx
    course: "k8s-crash-course"
    section: "02-3-Deployments"
  annotations:
    description: "Secure production-like NGINX deployment."
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        course: "k8s-crash-course"
        section: "02-3-Deployments"
      annotations:
        description: "Pod for production-like NGINX deployment."
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: cgr.dev/chainguard/nginx:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              cpu: "250m"
              memory: "50Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
