apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-minimal
  namespace: 02--service
  labels:
    app: nginx
    course: "k8s-crash-course"
    section: "02-4-Services"
  annotations:
    description: "Minimal NGINX deployment for the Service examples."
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-minimal
  template:
    metadata:
      labels:
        app: nginx-minimal
        course: "k8s-crash-course"
        section: "02-4-Services"
      annotations:
        description: "Minimal NGINX pod for the Service examples."
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx:1
