apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: 02--service
  labels:
    app: nginx-minimal
    course: "k8s-crash-course"
    section: "02-4-Services"
  annotations:
    description: "LoadBalancer service exposing NGINX pods."
    version: "1.0"
spec:
  type: LoadBalancer # Will only work if the cluster is configured to provision one from an external provider (e.g. Cloud Provider).
  selector:
    app: nginx-minimal
  ports:
    - protocol: TCP
      port: 80 # This is the port that the service will expose.
      targetPort: 80 # This is the port on the pod that the service will forward to.
