apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: 02--statefulset
  labels:
    app: redis-multi
    course: "k8s-crash-course"
    section: "02-8-StatefulSets"
  annotations:
    description: "Headless service exposing multiple Redis StatefulSet pods."
    version: "1.0"
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 # This is the port that the service will expose.
      targetPort: 6379 # This is the port on the pod that the service will forward to.

# This service will route traffic to multiple Redis pods created by the StatefulSet.
# It sets up a DNS for each replica in the StatefulSet, allowing direct access to each pod.
# Example: redis-0.redis-headless.default.svc.cluster.local
# This is useful for applications that need to communicate with specific pod instances.
