apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-with-init-container
  namespace: 02--statefulset
  labels:
    app: nginx-with-init-container
    course: "k8s-crash-course"
    section: "02-8-StatefulSets"
  annotations:
    description: "StatefulSet example for NGINX with an init container."
    version: "1.0"
spec:
  serviceName: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        course: "k8s-crash-course"
        section: "02-8-StatefulSets"
      annotations:
        description: "StatefulSet template for NGINX pods with an init container."
        version: "1.0"
    spec:
      initContainers:
        - name: populate-default-html
          image: nginx:1
          command:
            - bash
            - -c
            - |
              set -ex
              [[ ${HOSTNAME} =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo "<h1>Hello from pod ${HOSTNAME} with ordinal ${ordinal}</h1>" \
              > /usr/share/nginx/html/index.html
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:1
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: html-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        volumeMode: Filesystem
        resources:
          requests:
            storage: 100Mi
