apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: 02--secret
  labels:
    app: pod-with-secret
    course: "k8s-crash-course"
    section: "02-10-Secrets"
  annotations:
    description: "Pod example using Secrets."
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: nginx:1
      resources:
        limits:
          memory: "64Mi"
        requests:
          memory: "32Mi"
          cpu: "250m"
      volumeMounts:
        - name: secret-base64-data
          mountPath: /etc/config
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: base64-data
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: base64-data
              key: password
        - name: SECRET_API_KEY
          valueFrom:
            secretKeyRef:
              name: base64-data
              key: apiKey
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: base64-data
              key: token
  volumes:
    - name: secret-base64-data
      secret:
        secretName: base64-data
