apiVersion: v1
kind: Namespace
metadata:
  name: 02--secret
  labels:
    course: "k8s-crash-course"
    section: "02-10-Secrets"
  annotations:
    description: "Namespace for the Secret examples."
    version: "1.0"
