apiVersion: v1
kind: Secret
metadata:
  name: string-data
  namespace: 02--secret
  labels:
    app: secret-string-data
    course: "k8s-crash-course"
    section: "02-10-Secrets"
  annotations:
    description: "Secret with string data."
    version: "1.0"
type: Opaque
stringData:
  username: admin
  password: secret123
  apiKey: abcdefghijklmnopqrstuvwxyz
  token: "1234567890"
