apiVersion: v1
kind: Namespace
metadata:
  name: 02--ingress
  labels:
    course: "k8s-crash-course"
    section: "02-11-Ingress"
  annotations:
    description: "Namespace for Ingress examples."
    version: "1.0"
