apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-minimal
  namespace: 02--ingress
  labels:
    app: nginx-minimal
    course: "k8s-crash-course"
    section: "02-11-Ingress"
  annotations:
    description: "Minimal Deployment example for NGINX."
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-minimal
  template:
    metadata:
      labels:
        app: nginx-minimal
        course: "k8s-crash-course"
        section: "02-11-Ingress"
      annotations:
        description: "Deployment template for NGINX pods."
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx:1
