apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1-example
  namespace: 02--persistent-volume
  labels:
    app: pv-example
    course: "k8s-crash-course"
    section: "02-12-Persistent-Volumes"
  annotations:
    description: "PersistentVolume1 example."
    version: "1.0"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  local:
    path: /kind-bind-mount # Path in the container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2-example
  namespace: 02--persistent-volume
  labels:
    app: pv-example
    course: "k8s-crash-course"
    section: "02-12-Persistent-Volumes"
  annotations:
    description: "PersistentVolume2 example."
    version: "1.0"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  local:
    path: /kind-bind-mount # Path in the container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker2
