apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-dynamic-deployment
  namespace: 02--persistent-volume
  labels:
    app: pv-dynamic-deployment
    course: "k8s-crash-course"
    section: "02-12-Persistent-Volumes"
  annotations:
    description: "Deployment using dynamic PersistentVolume."
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1
          volumeMounts:
            - name: pv-dynamic-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pv-dynamic-storage
          persistentVolumeClaim:
            claimName: pv-dynamic-example
