# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: ${KIND_HOST_PATH}/kind-bind-mount-1
        containerPath: ${KIND_CONTAINER_PATH:-/kind-bind-mount}
  - role: worker
    extraMounts:
      - hostPath: ${KIND_HOST_PATH}/kind-bind-mount-2
        containerPath: ${KIND_CONTAINER_PATH:-/kind-bind-mount}
